/** @type {import('tailwindcss').Config} */
// Colours are CSS variables (src/palette.css, generated by scripts/gen-palette.mjs), so every existing utility follows the shared
// Optix palette without changing any component. The Optix suite is light only. See optix-suite-sdk/theme/README.md.
import { HUES, SHADES } from './scripts/gen-palette.mjs'

const v = (name) => `rgb(var(--${name}) / <alpha-value>)`
const pal = (kind) => Object.fromEntries(HUES.map((h) => [h, Object.fromEntries(SHADES.map((s) => [s, v(`${kind}-${h}-${s}`)]))]))
const bg = { ...pal('bg'), white: v('o-surface') }
const bd = { ...pal('bd'), white: v('o-surface') }

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: { sans: ['var(--font)'] },
      colors: Object.fromEntries(
        ['blue', 'blue-d', 'link', 'ink', 'text2', 'muted', 'line', 'bg', 'surface', 'surface2', 'tint', 'chip', 'teal', 'teal-tint', 'deep'].map((k) => [`o-${k}`, v(`o-${k}`)]),
      ),
      backgroundColor: bg,
      gradientColorStops: bg,
      textColor: pal('tx'),
      borderColor: bd,
      divideColor: bd,
      ringColor: bd,
      outlineColor: bd,
      borderRadius: { o: 'var(--r)', 'o-sm': 'var(--r-sm)', 'o-xs': 'var(--r-xs)' },
      boxShadow: { 'o-1': 'var(--shadow-1)', 'o-2': 'var(--shadow-2)', 'o-3': 'var(--shadow-3)' },
    },
  },
  plugins: [],
}
