// Generates src/palette.css: the colour variables behind the Tailwind palette and the Optix tokens (o-*). The Optix suite is light only.
//   node scripts/gen-palette.mjs
// tailwind.config.js reads these variables, so every existing utility (bg-slate-50, text-emerald-700, border-rose-200 ...)
// follows the Optix palette without touching the components. Tailwind defaults with a few Optix tweaks.
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const colors = require('tailwindcss/colors')
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

export const HUES = ['slate', 'gray', 'zinc', 'neutral', 'stone', 'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose']
export const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]
const NEUTRAL = ['slate', 'gray', 'zinc', 'neutral', 'stone']
const hex = (h) => { const n = h.replace('#', ''); return [0, 2, 4].map((i) => parseInt(n.slice(i, i + 2), 16)) }
const tri = (c) => (Array.isArray(c) ? c : hex(c)).join(' ')

const BLUE = { 400: [91, 140, 255], 500: [75, 125, 248], 600: [47, 109, 246], 700: [31, 79, 209], 800: [27, 66, 180], 900: [22, 52, 140] }
const TEAL_L = { 500: [20, 184, 166], 600: [14, 143, 128], 700: [13, 124, 112], 800: [11, 100, 91], 900: [10, 80, 74] }
const TEAL_D = [123, 224, 212]

// light --------------------------------------------------------------
function light(kind, hue, s) {
  const base = hex(colors[hue][s])
  if (NEUTRAL.includes(hue)) {
    if (kind === 'bg') return { 50: [246, 248, 252], 100: [240, 244, 251], 200: [228, 233, 244], 300: [207, 216, 234], 700: [48, 62, 105], 800: [27, 42, 90], 900: [16, 26, 61], 950: [11, 18, 48] }[s] || base
    if (kind === 'bd') return { 50: [240, 244, 251], 100: [236, 240, 248], 200: [228, 233, 244], 300: [207, 216, 234] }[s] || base
    return { 400: [90, 102, 132], 500: [90, 102, 132], 600: [77, 90, 121], 700: [60, 71, 97], 800: [27, 42, 74], 900: [20, 33, 61], 950: [14, 22, 45] }[s] || base
  }
  // the old primary colours of the app: green fills and indigo/blue become the Optix blue; green text becomes the teal accent
  if (hue === 'emerald') {
    if (kind === 'bg') return { 50: [230, 247, 244], 100: [207, 240, 234], 500: BLUE[500], 600: BLUE[600], 700: BLUE[700] }[s] || base
    if (kind === 'bd') return { 200: [183, 229, 220], 300: [150, 215, 203] }[s] || base
    return TEAL_L[s] || base
  }
  if (hue === 'indigo' || hue === 'blue') {
    if (kind === 'bg') return { 50: [234, 240, 255], 100: [219, 230, 255], 500: BLUE[500], 600: BLUE[600], 700: BLUE[700] }[s] || base
    if (kind === 'bd') return { 100: [219, 230, 255], 200: [195, 211, 250], 300: [160, 187, 248] }[s] || base
    return BLUE[s] || base
  }
  return base
}

const KINDS = ['bg', 'tx', 'bd']
const block = (fn) => HUES.flatMap((h) => KINDS.flatMap((k) => SHADES.map((s) => `--${k}-${h}-${s}:${tri(fn(k, h, s))}`))).join(';')

// Optix tokens as r g b triplets (same values as optix-suite-sdk/theme/optix-theme.css)
const TOK_LIGHT = {
  'o-blue': '47 109 246', 'o-blue-d': '31 79 209', 'o-link': '31 79 209', 'o-ink': '20 33 61', 'o-text2': '77 90 121', 'o-muted': '107 119 148', 'o-line': '228 233 244',
  'o-bg': '246 248 252', 'o-surface': '255 255 255', 'o-surface2': '250 251 255', 'o-tint': '234 240 255', 'o-chip': '240 244 251',
  'o-teal': '14 143 128', 'o-teal-tint': '230 247 244', 'o-deep': '16 26 61',
}
const toks = (o) => Object.entries(o).map(([k, v]) => `--${k}:${v}`).join(';')
const lightVars = `${toks(TOK_LIGHT)};${block(light)}`

const css = `/* GENERATED by scripts/gen-palette.mjs - do not edit by hand.
   Colour variables behind tailwind.config.js (Tailwind defaults with Optix tweaks). The Optix suite is light only. */
:root{${lightVars};color-scheme:light}
`
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(path.join(root, 'src', 'palette.css'), css)
  console.log('palette.css written,', css.length, 'bytes')
}
