// Reads the AdSense settings from public/medsync/ads-config.json and writes:
//   public/medsync/ads-config.js   window.OPTIX_ADS = { client, slots }   (read by the public pages)
//   public/ads.txt                 only when a valid publisher id is set; removed again when it is empty
//
//   1. edit public/medsync/ads-config.json:  { "client": "ca-pub-1234567890123456", "slots": { "home-mid": "1111111111", "home-end": "2222222222" } }
//   2. node scripts/make-ads-txt.mjs        (also runs automatically before `npm run build`)
// With an empty "client" nothing from Google is ever loaded and no ads.txt is published.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const cfgPath = path.join(root, 'public', 'medsync', 'ads-config.json')
const jsPath = path.join(root, 'public', 'medsync', 'ads-config.js')
const txtPath = path.join(root, 'public', 'ads.txt')

let cfg = { client: '', slots: {} }
try { cfg = { ...cfg, ...JSON.parse(fs.readFileSync(cfgPath, 'utf8')) } } catch { console.log('make-ads-txt: no ads-config.json, ads stay off') }

const client = String(cfg.client || '').trim()
const valid = /^ca-pub-\d{6,20}$/.test(client)
if (client && !valid) console.warn(`make-ads-txt: "${client}" is not a publisher id like ca-pub-1234567890123456, ads stay off`)
const slots = {}
for (const [k, v] of Object.entries(cfg.slots || {})) if (/^\d{6,20}$/.test(String(v))) slots[k] = String(v)

const out = { client: valid ? client : '', slots: valid ? slots : {} }
const js = `// Generated by scripts/make-ads-txt.mjs from ads-config.json. Do not edit.\nwindow.OPTIX_ADS=${JSON.stringify(out)};\n`
if (!fs.existsSync(jsPath) || fs.readFileSync(jsPath, 'utf8') !== js) fs.writeFileSync(jsPath, js)

if (valid) {
  fs.writeFileSync(txtPath, `google.com, ${client.replace(/^ca-/, '')}, DIRECT, f08c47fec0942fa0\n`)
  console.log('make-ads-txt: ads ON for', client, '- wrote public/ads.txt')
} else {
  fs.rmSync(txtPath, { force: true })
  console.log('make-ads-txt: ads OFF (no publisher id), no ads.txt')
}
