// Copies the shared Optix theme (design tokens + AdSense consent loader) from the SDK repo into the public pages.
//   node scripts/sync-theme.mjs
// Source of truth: ../optix-suite-sdk/theme  (do not edit the copies in public/medsync).
// If the SDK folder is not next to this repo (e.g. a CI build), the committed copies are kept and the script succeeds.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const from = path.resolve(root, process.env.OPTIX_SDK_DIR || '../optix-suite-sdk', 'theme')
const to = path.join(root, 'public', 'medsync')
const FILES = ['optix-theme.css', 'consent.js']

if (!fs.existsSync(from)) {
  console.log(`sync-theme: ${from} not found, keeping the committed copies in public/medsync`)
  process.exit(0)
}
// The Optix suite is light only: the dark-mode rules of the shared theme (:root[data-theme=dark]...) are removed from the copies.
const lightOnly = (css) => css.replace(/^[ \t]*:root\[data-theme=dark\][^{]*\{[^}]*\}[ \t]*\n?/gm, '')
for (const f of FILES) {
  let text = fs.readFileSync(path.join(from, f), 'utf8')
  if (f.endsWith('.css')) text = lightOnly(text)
  fs.writeFileSync(path.join(to, f), text)
  console.log('sync-theme: copied', f)
}

// The app (Tailwind) only needs the design tokens, not the website classes (.btn, .nav, .card ...): copy the two token blocks
// (light + dark, everything before the first element rule) into src/optix-tokens.css.
const css = lightOnly(fs.readFileSync(path.join(from, 'optix-theme.css'), 'utf8'))
const end = css.indexOf('\n*{box-sizing')
if (end < 0) throw new Error('sync-theme: token block not found in optix-theme.css')
const tokens = css.slice(css.indexOf(':root{'), end).trim()
fs.writeFileSync(path.join(root, 'src', 'optix-tokens.css'), `/* GENERATED by scripts/sync-theme.mjs from optix-suite-sdk/theme/optix-theme.css (tokens only). Do not edit. */\n${tokens}\n`)
console.log('sync-theme: wrote src/optix-tokens.css')
